### ISSUE TITLE
Add duplicate capcode filter between networks

### ISSUE THREAD

**Issue by melbournefan** [pagermon/pagermon#353] opened 2020-01-07 14:07 UTC
When capcodes are added, provide a option in the settings that 'binds' a capcode to one receiver (network), I'm starting to find that some capcodes are conflicting between networks

**Comment by davidmckenzie** [comment] 2020-01-07 21:55
Possibly dupe of #141 - I'm guessing you're thinking to separate them out based on the source field?

**Comment by melbournefan** [comment] 2020-01-08 02:36
Yup, one of the CFA capcodes on the EAS network is conflicting with a telematics capcode on Vodafone that I want to block

**Comment by DanrwAU** [comment] 2020-01-08 02:38
I filter this on the receiver side. 

Example from my reader.js 

`if ((address.length > 2 && message) && ((trimMessage.match(/E\d{11}/g)) || (trimMessage.match(/N\d{11}/g)) || (trimMessage.match(/J\d{11}/g)) || (trimMessage.match('Part 2 of 2')) || (trimMessage.match('Branch for cover')))) {    `

**Closed** 2020-01-18 09:01 UTC
Labels: DB, enhancement
